language: python
python:
- "3.6"
env:
- DJANGO=2.0 DB=sqlite3

global:
  - PGPORT=5432

install:
- pip install -r requirements.txt
script:
- cd tfg-alzheimer-webapp


branches:
   only:
     - master
